[2025-05-31T19:40:49.951-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chamar_api_vendas.chamar_api scheduled__2025-05-31T22:39:00+00:00 [queued]>
[2025-05-31T19:40:49.955-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chamar_api_vendas.chamar_api scheduled__2025-05-31T22:39:00+00:00 [queued]>
[2025-05-31T19:40:49.955-0300] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-31T19:40:49.965-0300] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): chamar_api> on 2025-05-31 22:39:00+00:00
[2025-05-31T19:40:49.972-0300] {standard_task_runner.py:60} INFO - Started process 11898 to run task
[2025-05-31T19:40:49.976-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'chamar_api_vendas', 'chamar_api', 'scheduled__2025-05-31T22:39:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/chamar_api_vendas.py', '--cfg-path', '/tmp/tmptuh7m49d']
[2025-05-31T19:40:49.977-0300] {standard_task_runner.py:88} INFO - Job 4: Subtask chamar_api
[2025-05-31T19:40:50.007-0300] {task_command.py:423} INFO - Running <TaskInstance: chamar_api_vendas.chamar_api scheduled__2025-05-31T22:39:00+00:00 [running]> on host walter-vjfe59f11xb1011h
[2025-05-31T19:40:50.047-0300] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='chamar_api_vendas' AIRFLOW_CTX_TASK_ID='chamar_api' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T22:39:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-31T22:39:00+00:00'
[2025-05-31T19:40:50.048-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-31T19:40:50.049-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "curl -X POST 'http://api-vendas:8002/gerar-vendas' -H 'accept: application/json' -d ''"]
[2025-05-31T19:40:50.062-0300] {subprocess.py:86} INFO - Output:
[2025-05-31T19:40:50.068-0300] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-05-31T19:40:50.069-0300] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-05-31T19:40:50.348-0300] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: api-vendas
[2025-05-31T19:40:50.350-0300] {subprocess.py:97} INFO - Command exited with return code 6
[2025-05-31T19:40:50.355-0300] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/walterg/Documentos/Data_projects/Data-Warehouse-postgres-DBT-airflow-/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/walterg/Documentos/Data_projects/Data-Warehouse-postgres-DBT-airflow-/.venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2025-05-31T19:40:50.358-0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=chamar_api_vendas, task_id=chamar_api, execution_date=20250531T223900, start_date=20250531T224049, end_date=20250531T224050
[2025-05-31T19:40:50.371-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task chamar_api (Bash command failed. The command returned a non-zero exit code 6.; 11898)
[2025-05-31T19:40:50.389-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-31T19:40:50.398-0300] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
